ASSERT-KTH/spork

- README.md
here, I use `merge` from package `rcs`. what are the other command-line mergers?
> doc: add link to merge

- .travis.yml
- pom.xml
> [misc] Add coverage tracking with Jacoco+Codecov

- src/main/java/se/kth/spork/cli/OperatorHelper.java
- src/main/java/se/kth/spork/cli/PrinterPreprocessor.java
- src/test/resources/conflict/conflicting_operator_change/Base.java
- src/test/resources/conflict/conflicting_operator_change/Expected.java
- src/test/resources/conflict/conflicting_operator_change/Left.java
- src/test/resources/conflict/conflicting_operator_change/Right.java
Fix #69 
Operator conflicts are now properly pretty-printed.
> [fix] Print operator conflicts

- src/main/java/se/kth/spork/base3dm/TdmMerge.java
- src/main/java/se/kth/spork/exception/ConflictException.java
- src/main/java/se/kth/spork/spoon/pcsinterpreter/ContentMerger.java
- src/main/java/se/kth/spork/spoon/pcsinterpreter/PcsInterpreter.java
- src/main/java/se/kth/spork/spoon/pcsinterpreter/SporkTreeBuilder.java
- src/main/java/se/kth/spork/spoon/printer/PrinterPreprocessor.java
- src/test/java/se/kth/spork/Util.java
- src/test/java/se/kth/spork/spoon/Spoon3dmMergeTest.java
- src/test/resources/unhandled_inconsistency/intra_parent_move_conflict/Base.java
- src/test/resources/unhandled_inconsistency/intra_parent_move_conflict/Left.java
- src/test/resources/unhandled_inconsistency/intra_parent_move_conflict/Right.java
> [fix] Fix flaky inconsistency detection

- src/main/java/se/kth/spork/spoon/Spoon3dmMerge.java
- src/test/resources/clean/both_modified/both_add_try/Base.java
- src/test/resources/clean/both_modified/both_add_try/Expected.java
- src/test/resources/clean/both_modified/both_add_try/Left.java
- src/test/resources/clean/both_modified/both_add_try/Right.java
> [fix] Use XY matcher for left-to-right matching

- src/main/java/se/kth/spork/util/LineBasedMerge.java
- src/test/java/se/kth/spork/cli/CliTest.java
- src/test/resources/clean/both_modified/add_file_header/Base.java
- src/test/resources/clean/both_modified/add_file_header/Expected.java
- src/test/resources/clean/both_modified/add_file_header/Left.java
- src/test/resources/clean/both_modified/add_file_header/Right.java
> [fix] Fix false positive conflict in line-based merge on pure addition

- .travis.yml
- .travis/install.sh
> [test] Update jarfile URLs

- replication/README.md
The replication package should generalize beyond the thesis.
> [docs] Remove references to the thesis from replication package

- pom.xml
Adds the Spoon snapshot repository to be able to use Spork with the latest snapshot of Spoon in the [Spoon Jenkins pipeline](https://ci.inria.fr/sos/)
> [misc] Add the Spoon snapshot repository

- pom.xml
Just updates Kotlin to a more recent version.
> [misc] Update Kotlin to version 1.4.31

- .github/workflows/tests.yml
> [misc] Add Maven dependency cache

- .github/workflows/tests.yml
- README.md
> [misc] Add macos build

- .github/workflows/tests.yml
> [misc] Run file merge benchmark only on master

- .github/workflows/tests.yml
> [misc] Use setup-java v2.0.0

- .github/workflows/tests.yml
> [misc] Remove version comments from GitHub Actions workflow

- pom.xml
- src/main/kotlin/se/kth/spork/spoon/Spoon3dmMerge.kt
- src/main/kotlin/se/kth/spork/spoon/pcsinterpreter/SpoonTreeBuilder.kt
Bumps Spoon version and fixes regression caused by inria/spoon#4099
> [misc] Bump Spoon version to 9.1.0

- .github/workflows/tests.yml
- pom.xml
Next release of Spoon requires Java 11, see inria/spoon#4173
> [break] Target Java 11

- CITATION.cff
- README.md
> [misc] Add CITATION.cff

- .github/workflows/tests.yml
- pom.xml
- src/main/java/se/kth/spork/spoon/printer/OperatorHelper.java
- src/main/kotlin/se/kth/spork/base3dm/TdmMerge.kt
- src/main/kotlin/se/kth/spork/spoon/ContentResolver.kt
- src/main/kotlin/se/kth/spork/spoon/Spoon3dmMerge.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/CommentContentHandler.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/ContentConflict.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/ContentConflictHandler.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/ContentMerger.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/IsImplicitHandler.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/IsUpperHandler.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/MethodOrderingConflictHandler.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/ModifierHandler.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/OptimisticInsertInsertHandler.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/StructuralConflict.kt
- src/main/kotlin/se/kth/spork/spoon/conflict/StructuralConflictHandler.kt
- src/main/kotlin/se/kth/spork/spoon/matching/ClassRepresentatives.kt
- src/main/kotlin/se/kth/spork/spoon/matching/SpoonMapping.kt
- src/main/kotlin/se/kth/spork/spoon/pcsinterpreter/PcsInterpreter.kt
- src/main/kotlin/se/kth/spork/spoon/pcsinterpreter/SpoonTreeBuilder.kt
- src/main/kotlin/se/kth/spork/spoon/pcsinterpreter/SporkTree.kt
- src/main/kotlin/se/kth/spork/spoon/pcsinterpreter/SporkTreeBuilder.kt
- src/main/kotlin/se/kth/spork/spoon/wrappers/NodeFactory.kt
- src/main/kotlin/se/kth/spork/spoon/wrappers/RoledValue.kt
- src/main/kotlin/se/kth/spork/util/LineBasedMerge.kt
- src/test/java/se/kth/spork/cli/CliTest.java
- src/test/java/se/kth/spork/spoon/Spoon3dmMergeTest.java
Updates a bunch of dependencies and the autoformatting (which was seemingly broken).
> [misc] Update dependencies and formatting

- README.md
cc/ @wetneb @benedikt-schesch @mernst
> redirects users to mergiraf
